version: "2"

services:
    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --requirepass socialtorcedor --user socialtorcedor
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - /home/${USER_NAME}/app/redis-data:/data

    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - /home/${USER_NAME}/app/mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=socialtorcedor
            - MONGO_INITDB_ROOT_PASSWORD=socialtorcedor

    back:
        build: "./server"
        container_name: server
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - /home/${USER_NAME}/app/server-node:/server
        environment:
            - REDIS_DB=redis
            - MONGO_DB=mongo
        depends_on:
            - redis
            - mongo

    front:
        build: "./client"
        container_name: client
        restart: always
        ports:
            - "8080:80"
        volumes:
            - /home/${USER_NAME}/app:/usr/nginx/
        depends_on:
            - back

networks:
    social_torcedor:
        driver: bridge
